#target photoshop
//
// change_back_dob.jsx
//

//
// Generated Tue Jan 06 2026 21:46:13 GMT+0500
//

cTID = function(s) { return app.charIDToTypeID(s); };
sTID = function(s) { return app.stringIDToTypeID(s); };

//
//==================== Sizes 3 ==============
//
function Sizes3() {
  // Select
  function step1(enabled, withDialog) {
    if (enabled != undefined && !enabled)
      return;
    var dialogMode = (withDialog ? DialogModes.ALL : DialogModes.NO);
    var desc1 = new ActionDescriptor();
    var ref1 = new ActionReference();
    ref1.putName(cTID('Lyr '), "DOB");
    desc1.putReference(cTID('null'), ref1);
    desc1.putBoolean(cTID('MkVs'), false);
    var list1 = new ActionList();
    list1.putInteger(7021);
    desc1.putList(cTID('LyrI'), list1);
    executeAction(cTID('slct'), desc1, dialogMode);
  };

  // Select
  function step2(enabled, withDialog) {
    if (enabled != undefined && !enabled)
      return;
    var dialogMode = (withDialog ? DialogModes.ALL : DialogModes.NO);
    var desc1 = new ActionDescriptor();
    var ref1 = new ActionReference();
    ref1.putEnumerated(cTID('Lyr '), cTID('Ordn'), cTID('Trgt'));
    desc1.putReference(cTID('null'), ref1);
    desc1.putBoolean(cTID('MkVs'), false);
    var list1 = new ActionList();
    list1.putInteger(7021);
    desc1.putList(cTID('LyrI'), list1);
    executeAction(cTID('slct'), desc1, dialogMode);
  };

  // Set
  function step3(enabled, withDialog) {
    if (enabled != undefined && !enabled)
      return;
    var dialogMode = (withDialog ? DialogModes.ALL : DialogModes.NO);
    var desc1 = new ActionDescriptor();
    var ref1 = new ActionReference();
    ref1.putEnumerated(cTID('TxLr'), cTID('Ordn'), cTID('Trgt'));
    desc1.putReference(cTID('null'), ref1);
    var desc2 = new ActionDescriptor();
    // desc2.putString(cTID('Txt '), "JUN 19 87");
    var desc3 = new ActionDescriptor();
    desc3.putEnumerated(sTID("warpStyle"), sTID("warpStyle"), sTID("warpNone"));
    desc3.putDouble(sTID("warpValue"), 0);
    desc3.putDouble(sTID("warpPerspective"), 0);
    desc3.putDouble(sTID("warpPerspectiveOther"), 0);
    desc3.putEnumerated(sTID("warpRotate"), cTID('Ornt'), cTID('Hrzn'));
    desc2.putObject(cTID('warp'), cTID('warp'), desc3);
    desc2.putEnumerated(sTID("textGridding"), sTID("textGridding"), cTID('None'));
    desc2.putEnumerated(cTID('Ornt'), cTID('Ornt'), cTID('Hrzn'));
    desc2.putEnumerated(cTID('AntA'), cTID('Annt'), cTID('AnSm'));
    var desc4 = new ActionDescriptor();
    desc4.putUnitDouble(cTID('Left'), cTID('#Pxl'), -299.763763427734);
    desc4.putUnitDouble(cTID('Top '), cTID('#Pxl'), -536.855346679688);
    desc4.putUnitDouble(cTID('Rght'), cTID('#Pxl'), 314.552642822266);
    desc4.putUnitDouble(cTID('Btom'), cTID('#Pxl'), 1119.20654296875);
    desc2.putObject(sTID("bounds"), sTID("bounds"), desc4);
    var desc5 = new ActionDescriptor();
    desc5.putUnitDouble(cTID('Left'), cTID('#Pxl'), -240.626937866211);
    desc5.putUnitDouble(cTID('Top '), cTID('#Pxl'), -309.621124267578);
    desc5.putUnitDouble(cTID('Rght'), cTID('#Pxl'), 175.825729370117);
    desc5.putUnitDouble(cTID('Btom'), cTID('#Pxl'), 1099.93310546875);
    desc2.putObject(sTID("boundingBox"), sTID("boundingBox"), desc5);
    var list1 = new ActionList();
    var desc6 = new ActionDescriptor();
    var desc7 = new ActionDescriptor();
    var list2 = new ActionList();
    var desc8 = new ActionDescriptor();
    desc8.putEnumerated(sTID("shapeOperation"), sTID("shapeOperation"), sTID("xor"));
    var list3 = new ActionList();
    var desc9 = new ActionDescriptor();
    var list4 = new ActionList();
    var desc10 = new ActionDescriptor();
    var desc11 = new ActionDescriptor();
    desc11.putUnitDouble(cTID('Hrzn'), cTID('#Pxl'), 0);
    desc11.putUnitDouble(cTID('Vrtc'), cTID('#Pxl'), 1113);
    desc10.putObject(cTID('Anch'), cTID('Pnt '), desc11);
    var desc12 = new ActionDescriptor();
    desc12.putUnitDouble(cTID('Hrzn'), cTID('#Pxl'), 12.1243896484375);
    desc12.putUnitDouble(cTID('Vrtc'), cTID('#Pxl'), 883.664184570312);
    desc10.putObject(cTID('Fwd '), cTID('Pnt '), desc12);
    var desc13 = new ActionDescriptor();
    desc13.putUnitDouble(cTID('Hrzn'), cTID('#Pxl'), 0);
    desc13.putUnitDouble(cTID('Vrtc'), cTID('#Pxl'), 1113);
    desc10.putObject(cTID('Bwd '), cTID('Pnt '), desc13);
    desc10.putBoolean(cTID('Smoo'), false);
    list4.putObject(cTID('Pthp'), desc10);
    var desc14 = new ActionDescriptor();
    var desc15 = new ActionDescriptor();
    desc15.putUnitDouble(cTID('Hrzn'), cTID('#Pxl'), 243);
    desc15.putUnitDouble(cTID('Vrtc'), cTID('#Pxl'), -536.855346679688);
    desc14.putObject(cTID('Anch'), cTID('Pnt '), desc15);
    var desc16 = new ActionDescriptor();
    desc16.putUnitDouble(cTID('Hrzn'), cTID('#Pxl'), 354.124389648438);
    desc16.putUnitDouble(cTID('Vrtc'), cTID('#Pxl'), -894.977340698242);
    desc14.putObject(cTID('Fwd '), cTID('Pnt '), desc16);
    var desc17 = new ActionDescriptor();
    desc17.putUnitDouble(cTID('Hrzn'), cTID('#Pxl'), 131.875610351562);
    desc17.putUnitDouble(cTID('Vrtc'), cTID('#Pxl'), -178.733352661133);
    desc14.putObject(cTID('Bwd '), cTID('Pnt '), desc17);
    desc14.putBoolean(cTID('Smoo'), true);
    list4.putObject(cTID('Pthp'), desc14);
    desc9.putList(cTID('Pts '), list4);
    list3.putObject(cTID('Sbpl'), desc9);
    desc8.putList(cTID('SbpL'), list3);
    list2.putObject(cTID('PaCm'), desc8);
    desc7.putList(sTID("pathComponents"), list2);
    desc6.putObject(cTID('Path'), sTID("pathClass"), desc7);
    var desc18 = new ActionDescriptor();
    desc18.putDouble(cTID('Strt'), 0);
    desc18.putDouble(cTID('End '), 0.9990000128746);
    desc6.putObject(sTID("tRange"), cTID('Rang'), desc18);
    desc6.putEnumerated(sTID("textType"), sTID("textType"), sTID("onACurve"));
    desc6.putEnumerated(cTID('Ornt'), cTID('Ornt'), cTID('Hrzn'));
    var desc19 = new ActionDescriptor();
    desc19.putDouble(sTID("xx"), 1);
    desc19.putDouble(sTID("xy"), 0);
    desc19.putDouble(sTID("yx"), 0);
    desc19.putDouble(sTID("yy"), 1);
    desc19.putDouble(sTID("tx"), 0);
    desc19.putDouble(sTID("ty"), 0);
    desc6.putObject(cTID('Trnf'), cTID('Trnf'), desc19);
    desc6.putInteger(sTID("rowCount"), 1);
    desc6.putInteger(sTID("columnCount"), 1);
    desc6.putBoolean(sTID("rowMajorOrder"), true);
    desc6.putUnitDouble(sTID("rowGutter"), cTID('#Pxl'), 0);
    desc6.putUnitDouble(sTID("columnGutter"), cTID('#Pxl'), 0);
    desc6.putUnitDouble(cTID('Spcn'), cTID('#Pxl'), 0);
    desc6.putEnumerated(sTID("frameBaselineAlignment"), sTID("frameBaselineAlignment"), sTID("alignByAscent"));
    desc6.putUnitDouble(sTID("firstBaselineMinimum"), cTID('#Pxl'), 0);
    desc6.putBoolean(cTID('Flip'), false);
    desc6.putEnumerated(sTID("pathTypeEffect"), sTID("pathTypeEffect"), sTID("rainbowEffect"));
    desc6.putEnumerated(sTID("pathTypeAlignment"), sTID("pathTypeAlignment"), sTID("baselineAlignment"));
    desc6.putEnumerated(sTID("pathTypeAlignTo"), sTID("pathTypeAlignTo"), sTID("toPathTop"));
    desc6.putInteger(sTID("pathTypeSpacing"), 0);
    list1.putObject(sTID("textShape"), desc6);
    desc2.putList(sTID("textShape"), list1);
    var list5 = new ActionList();
    var desc20 = new ActionDescriptor();
    desc20.putInteger(cTID('From'), 0);
    desc20.putInteger(cTID('T   '), 1);
    var desc21 = new ActionDescriptor();
    desc21.putBoolean(sTID("styleSheetHasParent"), true);
    desc21.putString(sTID("fontPostScriptName"), "Arial-Black");
    desc21.putString(cTID('FntN'), "Arial");
    desc21.putString(cTID('FntS'), "Black");
    desc21.putInteger(cTID('Scrp'), 0);
    desc21.putInteger(cTID('FntT'), 1);
    desc21.putBoolean(sTID("fontAvailable"), true);
    desc21.putUnitDouble(cTID('Sz  '), cTID('#Pxl'), 350);
    desc21.putUnitDouble(sTID("impliedFontSize"), cTID('#Pxl'), 350.00000000012);
    desc21.putDouble(cTID('HrzS'), 92.9999947547913);
    desc21.putDouble(cTID('VrtS'), 100);
    desc21.putBoolean(sTID("syntheticBold"), false);
    desc21.putBoolean(sTID("syntheticItalic"), false);
    desc21.putBoolean(sTID("autoLeading"), false);
    desc21.putUnitDouble(cTID('Ldng'), cTID('#Pxl'), 516.66650390625);
    desc21.putUnitDouble(sTID("impliedLeading"), cTID('#Pxl'), 516.666503906427);
    desc21.putInteger(cTID('Trck'), 25);
    desc21.putUnitDouble(cTID('Bsln'), cTID('#Pxl'), 0);
    desc21.putUnitDouble(sTID("impliedBaselineShift"), cTID('#Pxl'), 0);
    desc21.putEnumerated(cTID('AtKr'), cTID('AtKr'), sTID("manual"));
    desc21.putEnumerated(sTID("fontCaps"), sTID("fontCaps"), cTID('Nrml'));
    desc21.putEnumerated(sTID("digitSet"), sTID("digitSet"), sTID("arabicDigits"));
    desc21.putEnumerated(sTID("kashidas"), sTID("kashidas"), sTID("kashidaDefault"));
    desc21.putUnitDouble(sTID("diacXOffset"), cTID('#Pxl'), 0);
    desc21.putUnitDouble(sTID("diacYOffset"), cTID('#Pxl'), 0);
    desc21.putUnitDouble(sTID("markYDistFromBaseline"), cTID('#Pxl'), 0);
    desc21.putEnumerated(sTID("baseline"), sTID("baseline"), cTID('Nrml'));
    desc21.putEnumerated(sTID("strikethrough"), sTID("strikethrough"), sTID("strikethroughOff"));
    desc21.putEnumerated(cTID('Undl'), cTID('Undl'), sTID("underlineOff"));
    desc21.putBoolean(sTID("ligature"), true);
    desc21.putBoolean(sTID("altligature"), false);
    desc21.putBoolean(sTID("contextualLigatures"), true);
    desc21.putBoolean(sTID("fractions"), false);
    desc21.putBoolean(sTID("ordinals"), false);
    desc21.putBoolean(sTID("swash"), false);
    desc21.putBoolean(sTID("titling"), false);
    desc21.putBoolean(sTID("connectionForms"), false);
    desc21.putBoolean(sTID("stylisticAlternates"), false);
    desc21.putBoolean(sTID("ornaments"), false);
    desc21.putBoolean(sTID("justificationAlternates"), false);
    desc21.putEnumerated(sTID("figureStyle"), sTID("figureStyle"), cTID('Nrml'));
    desc21.putBoolean(sTID("proportionalMetrics"), false);
    desc21.putBoolean(cTID('kana'), false);
    desc21.putBoolean(sTID("italics"), false);
    desc21.putEnumerated(sTID("baselineDirection"), sTID("baselineDirection"), sTID("withStream"));
    desc21.putEnumerated(sTID("textLanguage"), sTID("textLanguage"), sTID("englishLanguage"));
    desc21.putEnumerated(sTID("japaneseAlternate"), sTID("japaneseAlternate"), sTID("defaultForm"));
    desc21.putDouble(sTID("mojiZume"), 0);
    desc21.putEnumerated(sTID("gridAlignment"), sTID("gridAlignment"), sTID("roman"));
    desc21.putBoolean(sTID("noBreak"), false);
    var desc22 = new ActionDescriptor();
    desc22.putDouble(cTID('Rd  '), 255);
    desc22.putDouble(cTID('Grn '), 255);
    desc22.putDouble(cTID('Bl  '), 255);
    desc21.putObject(cTID('Clr '), sTID("RGBColor"), desc22);
    var desc23 = new ActionDescriptor();
    desc23.putDouble(cTID('Rd  '), 255);
    desc23.putDouble(cTID('Grn '), 255);
    desc23.putDouble(cTID('Bl  '), 255);
    desc21.putObject(sTID("strokeColor"), sTID("RGBColor"), desc23);
    var desc24 = new ActionDescriptor();
    desc24.putString(sTID("fontPostScriptName"), "MyriadPro-Regular");
    desc24.putString(cTID('FntN'), "Myriad Pro");
    desc24.putString(cTID('FntS'), "Regular");
    desc24.putInteger(cTID('Scrp'), 0);
    desc24.putInteger(cTID('FntT'), 0);
    desc24.putBoolean(sTID("fontAvailable"), true);
    desc24.putUnitDouble(cTID('Sz  '), cTID('#Pxl'), 12);
    desc24.putUnitDouble(sTID("impliedFontSize"), cTID('#Pxl'), 12.0000000000041);
    desc24.putDouble(cTID('HrzS'), 100);
    desc24.putDouble(cTID('VrtS'), 100);
    desc24.putBoolean(sTID("syntheticBold"), false);
    desc24.putBoolean(sTID("syntheticItalic"), false);
    desc24.putBoolean(sTID("autoLeading"), true);
    desc24.putInteger(cTID('Trck'), 0);
    desc24.putUnitDouble(cTID('Bsln'), cTID('#Pxl'), 0);
    desc24.putUnitDouble(sTID("impliedBaselineShift"), cTID('#Pxl'), 0);
    desc24.putDouble(sTID("characterRotation"), 0);
    desc24.putEnumerated(cTID('AtKr'), cTID('AtKr'), sTID("metricsKern"));
    desc24.putEnumerated(sTID("fontCaps"), sTID("fontCaps"), cTID('Nrml'));
    desc24.putEnumerated(sTID("digitSet"), sTID("digitSet"), sTID("defaultDigits"));
    desc24.putEnumerated(sTID("dirOverride"), sTID("dirOverride"), sTID("dirOverrideDefault"));
    desc24.putEnumerated(sTID("kashidas"), sTID("kashidas"), sTID("kashidaDefault"));
    desc24.putEnumerated(sTID("diacVPos"), sTID("diacVPos"), sTID("diacVPosOpenType"));
    desc24.putUnitDouble(sTID("diacXOffset"), cTID('#Pxl'), 0);
    desc24.putUnitDouble(sTID("diacYOffset"), cTID('#Pxl'), 0);
    desc24.putUnitDouble(sTID("markYDistFromBaseline"), cTID('#Pxl'), 100);
    desc24.putEnumerated(sTID("baseline"), sTID("baseline"), cTID('Nrml'));
    desc24.putEnumerated(sTID("otbaseline"), sTID("otbaseline"), cTID('Nrml'));
    desc24.putEnumerated(sTID("strikethrough"), sTID("strikethrough"), sTID("strikethroughOff"));
    desc24.putEnumerated(cTID('Undl'), cTID('Undl'), sTID("underlineOff"));
    desc24.putUnitDouble(sTID("underlineOffset"), cTID('#Pxl'), 0);
    desc24.putBoolean(sTID("ligature"), true);
    desc24.putBoolean(sTID("altligature"), false);
    desc24.putBoolean(sTID("contextualLigatures"), false);
    desc24.putBoolean(sTID("alternateLigatures"), false);
    desc24.putBoolean(sTID("oldStyle"), false);
    desc24.putBoolean(sTID("fractions"), false);
    desc24.putBoolean(sTID("ordinals"), false);
    desc24.putBoolean(sTID("swash"), false);
    desc24.putBoolean(sTID("titling"), false);
    desc24.putBoolean(sTID("connectionForms"), false);
    desc24.putBoolean(sTID("stylisticAlternates"), false);
    desc24.putInteger(sTID("stylisticSets"), 0);
    desc24.putBoolean(sTID("ornaments"), false);
    desc24.putBoolean(sTID("justificationAlternates"), false);
    desc24.putEnumerated(sTID("figureStyle"), sTID("figureStyle"), cTID('Nrml'));
    desc24.putBoolean(sTID("proportionalMetrics"), false);
    desc24.putBoolean(cTID('kana'), false);
    desc24.putBoolean(sTID("italics"), false);
    desc24.putBoolean(cTID('ruby'), false);
    desc24.putEnumerated(sTID("baselineDirection"), sTID("baselineDirection"), sTID("rotated"));
    desc24.putEnumerated(sTID("textLanguage"), sTID("textLanguage"), sTID("englishLanguage"));
    desc24.putEnumerated(sTID("japaneseAlternate"), sTID("japaneseAlternate"), sTID("defaultForm"));
    desc24.putDouble(sTID("mojiZume"), 0);
    desc24.putEnumerated(sTID("gridAlignment"), sTID("gridAlignment"), sTID("roman"));
    desc24.putBoolean(sTID("enableWariChu"), false);
    desc24.putInteger(sTID("wariChuCount"), 2);
    desc24.putInteger(sTID("wariChuLineGap"), 0);
    desc24.putDouble(sTID("wariChuScale"), 0.5);
    desc24.putInteger(sTID("wariChuWidow"), 2);
    desc24.putInteger(sTID("wariChuOrphan"), 2);
    desc24.putEnumerated(sTID("wariChuJustification"), sTID("wariChuJustification"), sTID("wariChuAutoJustify"));
    desc24.putInteger(sTID("tcyUpDown"), 0);
    desc24.putInteger(sTID("tcyLeftRight"), 0);
    desc24.putDouble(sTID("leftAki"), -1);
    desc24.putDouble(sTID("rightAki"), -1);
    desc24.putInteger(sTID("jiDori"), 0);
    desc24.putBoolean(sTID("noBreak"), false);
    var desc25 = new ActionDescriptor();
    desc25.putDouble(cTID('Rd  '), 0);
    desc25.putDouble(cTID('Grn '), 0);
    desc25.putDouble(cTID('Bl  '), 0);
    desc24.putObject(cTID('Clr '), sTID("RGBColor"), desc25);
    var desc26 = new ActionDescriptor();
    desc26.putDouble(cTID('Rd  '), 0);
    desc26.putDouble(cTID('Grn '), 0);
    desc26.putDouble(cTID('Bl  '), 0);
    desc24.putObject(sTID("strokeColor"), sTID("RGBColor"), desc26);
    desc24.putBoolean(cTID('Fl  '), true);
    desc24.putBoolean(cTID('Strk'), false);
    desc24.putBoolean(sTID("fillFirst"), true);
    desc24.putBoolean(sTID("fillOverPrint"), false);
    desc24.putBoolean(sTID("strokeOverPrint"), false);
    desc24.putEnumerated(sTID("lineCap"), sTID("lineCap"), sTID("buttCap"));
    desc24.putEnumerated(sTID("lineJoin"), sTID("lineJoin"), sTID("miterJoin"));
    desc24.putUnitDouble(sTID("lineWidth"), cTID('#Pxl'), 1);
    desc24.putUnitDouble(sTID("miterLimit"), cTID('#Pxl'), 4);
    desc24.putDouble(sTID("lineDashoffset"), 0);
    desc21.putObject(sTID("baseParentStyle"), cTID('TxtS'), desc24);
    desc20.putObject(cTID('TxtS'), cTID('TxtS'), desc21);
    list5.putObject(cTID('Txtt'), desc20);
    var desc27 = new ActionDescriptor();
    desc27.putInteger(cTID('From'), 1);
    desc27.putInteger(cTID('T   '), 2);
    var desc28 = new ActionDescriptor();
    desc28.putBoolean(sTID("styleSheetHasParent"), true);
    desc28.putString(sTID("fontPostScriptName"), "Arial-Black");
    desc28.putString(cTID('FntN'), "Arial");
    desc28.putString(cTID('FntS'), "Black");
    desc28.putInteger(cTID('Scrp'), 0);
    desc28.putInteger(cTID('FntT'), 1);
    desc28.putBoolean(sTID("fontAvailable"), true);
    desc28.putUnitDouble(cTID('Sz  '), cTID('#Pxl'), 316.670013427734);
    desc28.putUnitDouble(sTID("impliedFontSize"), cTID('#Pxl'), 316.670013427843);
    desc28.putDouble(cTID('HrzS'), 92.9999947547913);
    desc28.putDouble(cTID('VrtS'), 100);
    desc28.putBoolean(sTID("syntheticBold"), false);
    desc28.putBoolean(sTID("syntheticItalic"), false);
    desc28.putBoolean(sTID("autoLeading"), false);
    desc28.putUnitDouble(cTID('Ldng'), cTID('#Pxl'), 516.66650390625);
    desc28.putUnitDouble(sTID("impliedLeading"), cTID('#Pxl'), 516.666503906427);
    desc28.putInteger(cTID('Trck'), 25);
    desc28.putUnitDouble(cTID('Bsln'), cTID('#Pxl'), 0);
    desc28.putUnitDouble(sTID("impliedBaselineShift"), cTID('#Pxl'), 0);
    desc28.putEnumerated(cTID('AtKr'), cTID('AtKr'), sTID("manual"));
    desc28.putEnumerated(sTID("fontCaps"), sTID("fontCaps"), cTID('Nrml'));
    desc28.putEnumerated(sTID("digitSet"), sTID("digitSet"), sTID("arabicDigits"));
    desc28.putEnumerated(sTID("kashidas"), sTID("kashidas"), sTID("kashidaDefault"));
    desc28.putUnitDouble(sTID("diacXOffset"), cTID('#Pxl'), 0);
    desc28.putUnitDouble(sTID("diacYOffset"), cTID('#Pxl'), 0);
    desc28.putUnitDouble(sTID("markYDistFromBaseline"), cTID('#Pxl'), 0);
    desc28.putEnumerated(sTID("baseline"), sTID("baseline"), cTID('Nrml'));
    desc28.putEnumerated(sTID("strikethrough"), sTID("strikethrough"), sTID("strikethroughOff"));
    desc28.putEnumerated(cTID('Undl'), cTID('Undl'), sTID("underlineOff"));
    desc28.putBoolean(sTID("ligature"), true);
    desc28.putBoolean(sTID("altligature"), false);
    desc28.putBoolean(sTID("contextualLigatures"), true);
    desc28.putBoolean(sTID("fractions"), false);
    desc28.putBoolean(sTID("ordinals"), false);
    desc28.putBoolean(sTID("swash"), false);
    desc28.putBoolean(sTID("titling"), false);
    desc28.putBoolean(sTID("connectionForms"), false);
    desc28.putBoolean(sTID("stylisticAlternates"), false);
    desc28.putBoolean(sTID("ornaments"), false);
    desc28.putBoolean(sTID("justificationAlternates"), false);
    desc28.putEnumerated(sTID("figureStyle"), sTID("figureStyle"), cTID('Nrml'));
    desc28.putBoolean(sTID("proportionalMetrics"), false);
    desc28.putBoolean(cTID('kana'), false);
    desc28.putBoolean(sTID("italics"), false);
    desc28.putEnumerated(sTID("baselineDirection"), sTID("baselineDirection"), sTID("withStream"));
    desc28.putEnumerated(sTID("textLanguage"), sTID("textLanguage"), sTID("englishLanguage"));
    desc28.putEnumerated(sTID("japaneseAlternate"), sTID("japaneseAlternate"), sTID("defaultForm"));
    desc28.putDouble(sTID("mojiZume"), 0);
    desc28.putEnumerated(sTID("gridAlignment"), sTID("gridAlignment"), sTID("roman"));
    desc28.putBoolean(sTID("noBreak"), false);
    var desc29 = new ActionDescriptor();
    desc29.putDouble(cTID('Rd  '), 255);
    desc29.putDouble(cTID('Grn '), 255);
    desc29.putDouble(cTID('Bl  '), 255);
    desc28.putObject(cTID('Clr '), sTID("RGBColor"), desc29);
    var desc30 = new ActionDescriptor();
    desc30.putDouble(cTID('Rd  '), 255);
    desc30.putDouble(cTID('Grn '), 255);
    desc30.putDouble(cTID('Bl  '), 255);
    desc28.putObject(sTID("strokeColor"), sTID("RGBColor"), desc30);
    desc27.putObject(cTID('TxtS'), cTID('TxtS'), desc28);
    list5.putObject(cTID('Txtt'), desc27);
    var desc31 = new ActionDescriptor();
    desc31.putInteger(cTID('From'), 2);
    desc31.putInteger(cTID('T   '), 3);
    var desc32 = new ActionDescriptor();
    desc32.putBoolean(sTID("styleSheetHasParent"), true);
    desc32.putString(sTID("fontPostScriptName"), "Arial-Black");
    desc32.putString(cTID('FntN'), "Arial");
    desc32.putString(cTID('FntS'), "Black");
    desc32.putInteger(cTID('Scrp'), 0);
    desc32.putInteger(cTID('FntT'), 1);
    desc32.putBoolean(sTID("fontAvailable"), true);
    desc32.putUnitDouble(cTID('Sz  '), cTID('#Pxl'), 300);
    desc32.putUnitDouble(sTID("impliedFontSize"), cTID('#Pxl'), 300.000000000103);
    desc32.putDouble(cTID('HrzS'), 92.9999947547913);
    desc32.putDouble(cTID('VrtS'), 100);
    desc32.putBoolean(sTID("syntheticBold"), false);
    desc32.putBoolean(sTID("syntheticItalic"), false);
    desc32.putBoolean(sTID("autoLeading"), false);
    desc32.putUnitDouble(cTID('Ldng'), cTID('#Pxl'), 516.66650390625);
    desc32.putUnitDouble(sTID("impliedLeading"), cTID('#Pxl'), 516.666503906427);
    desc32.putInteger(cTID('Trck'), 25);
    desc32.putUnitDouble(cTID('Bsln'), cTID('#Pxl'), 0);
    desc32.putUnitDouble(sTID("impliedBaselineShift"), cTID('#Pxl'), 0);
    desc32.putEnumerated(cTID('AtKr'), cTID('AtKr'), sTID("manual"));
    desc32.putEnumerated(sTID("fontCaps"), sTID("fontCaps"), cTID('Nrml'));
    desc32.putEnumerated(sTID("digitSet"), sTID("digitSet"), sTID("arabicDigits"));
    desc32.putEnumerated(sTID("kashidas"), sTID("kashidas"), sTID("kashidaDefault"));
    desc32.putUnitDouble(sTID("diacXOffset"), cTID('#Pxl'), 0);
    desc32.putUnitDouble(sTID("diacYOffset"), cTID('#Pxl'), 0);
    desc32.putUnitDouble(sTID("markYDistFromBaseline"), cTID('#Pxl'), 0);
    desc32.putEnumerated(sTID("baseline"), sTID("baseline"), cTID('Nrml'));
    desc32.putEnumerated(sTID("strikethrough"), sTID("strikethrough"), sTID("strikethroughOff"));
    desc32.putEnumerated(cTID('Undl'), cTID('Undl'), sTID("underlineOff"));
    desc32.putBoolean(sTID("ligature"), true);
    desc32.putBoolean(sTID("altligature"), false);
    desc32.putBoolean(sTID("contextualLigatures"), true);
    desc32.putBoolean(sTID("fractions"), false);
    desc32.putBoolean(sTID("ordinals"), false);
    desc32.putBoolean(sTID("swash"), false);
    desc32.putBoolean(sTID("titling"), false);
    desc32.putBoolean(sTID("connectionForms"), false);
    desc32.putBoolean(sTID("stylisticAlternates"), false);
    desc32.putBoolean(sTID("ornaments"), false);
    desc32.putBoolean(sTID("justificationAlternates"), false);
    desc32.putEnumerated(sTID("figureStyle"), sTID("figureStyle"), cTID('Nrml'));
    desc32.putBoolean(sTID("proportionalMetrics"), false);
    desc32.putBoolean(cTID('kana'), false);
    desc32.putBoolean(sTID("italics"), false);
    desc32.putEnumerated(sTID("baselineDirection"), sTID("baselineDirection"), sTID("withStream"));
    desc32.putEnumerated(sTID("textLanguage"), sTID("textLanguage"), sTID("englishLanguage"));
    desc32.putEnumerated(sTID("japaneseAlternate"), sTID("japaneseAlternate"), sTID("defaultForm"));
    desc32.putDouble(sTID("mojiZume"), 0);
    desc32.putEnumerated(sTID("gridAlignment"), sTID("gridAlignment"), sTID("roman"));
    desc32.putBoolean(sTID("noBreak"), false);
    var desc33 = new ActionDescriptor();
    desc33.putDouble(cTID('Rd  '), 255);
    desc33.putDouble(cTID('Grn '), 255);
    desc33.putDouble(cTID('Bl  '), 255);
    desc32.putObject(cTID('Clr '), sTID("RGBColor"), desc33);
    var desc34 = new ActionDescriptor();
    desc34.putDouble(cTID('Rd  '), 255);
    desc34.putDouble(cTID('Grn '), 255);
    desc34.putDouble(cTID('Bl  '), 255);
    desc32.putObject(sTID("strokeColor"), sTID("RGBColor"), desc34);
    desc31.putObject(cTID('TxtS'), cTID('TxtS'), desc32);
    list5.putObject(cTID('Txtt'), desc31);
    var desc35 = new ActionDescriptor();
    desc35.putInteger(cTID('From'), 3);
    desc35.putInteger(cTID('T   '), 4);
    var desc36 = new ActionDescriptor();
    desc36.putBoolean(sTID("styleSheetHasParent"), true);
    desc36.putString(sTID("fontPostScriptName"), "Arial-Black");
    desc36.putString(cTID('FntN'), "Arial");
    desc36.putString(cTID('FntS'), "Black");
    desc36.putInteger(cTID('Scrp'), 0);
    desc36.putInteger(cTID('FntT'), 1);
    desc36.putBoolean(sTID("fontAvailable"), true);
    desc36.putUnitDouble(cTID('Sz  '), cTID('#Pxl'), 350);
    desc36.putUnitDouble(sTID("impliedFontSize"), cTID('#Pxl'), 350.00000000012);
    desc36.putDouble(cTID('HrzS'), 92.9999947547913);
    desc36.putDouble(cTID('VrtS'), 100);
    desc36.putBoolean(sTID("syntheticBold"), false);
    desc36.putBoolean(sTID("syntheticItalic"), false);
    desc36.putBoolean(sTID("autoLeading"), false);
    desc36.putUnitDouble(cTID('Ldng'), cTID('#Pxl'), 516.66650390625);
    desc36.putUnitDouble(sTID("impliedLeading"), cTID('#Pxl'), 516.666503906427);
    desc36.putInteger(cTID('Trck'), 25);
    desc36.putUnitDouble(cTID('Bsln'), cTID('#Pxl'), 0);
    desc36.putUnitDouble(sTID("impliedBaselineShift"), cTID('#Pxl'), 0);
    desc36.putEnumerated(cTID('AtKr'), cTID('AtKr'), sTID("manual"));
    desc36.putEnumerated(sTID("fontCaps"), sTID("fontCaps"), cTID('Nrml'));
    desc36.putEnumerated(sTID("digitSet"), sTID("digitSet"), sTID("arabicDigits"));
    desc36.putEnumerated(sTID("kashidas"), sTID("kashidas"), sTID("kashidaDefault"));
    desc36.putUnitDouble(sTID("diacXOffset"), cTID('#Pxl'), 0);
    desc36.putUnitDouble(sTID("diacYOffset"), cTID('#Pxl'), 0);
    desc36.putUnitDouble(sTID("markYDistFromBaseline"), cTID('#Pxl'), 0);
    desc36.putEnumerated(sTID("baseline"), sTID("baseline"), cTID('Nrml'));
    desc36.putEnumerated(sTID("strikethrough"), sTID("strikethrough"), sTID("strikethroughOff"));
    desc36.putEnumerated(cTID('Undl'), cTID('Undl'), sTID("underlineOff"));
    desc36.putBoolean(sTID("ligature"), true);
    desc36.putBoolean(sTID("altligature"), false);
    desc36.putBoolean(sTID("contextualLigatures"), true);
    desc36.putBoolean(sTID("fractions"), false);
    desc36.putBoolean(sTID("ordinals"), false);
    desc36.putBoolean(sTID("swash"), false);
    desc36.putBoolean(sTID("titling"), false);
    desc36.putBoolean(sTID("connectionForms"), false);
    desc36.putBoolean(sTID("stylisticAlternates"), false);
    desc36.putBoolean(sTID("ornaments"), false);
    desc36.putBoolean(sTID("justificationAlternates"), false);
    desc36.putEnumerated(sTID("figureStyle"), sTID("figureStyle"), cTID('Nrml'));
    desc36.putBoolean(sTID("proportionalMetrics"), false);
    desc36.putBoolean(cTID('kana'), false);
    desc36.putBoolean(sTID("italics"), false);
    desc36.putEnumerated(sTID("baselineDirection"), sTID("baselineDirection"), sTID("withStream"));
    desc36.putEnumerated(sTID("textLanguage"), sTID("textLanguage"), sTID("englishLanguage"));
    desc36.putEnumerated(sTID("japaneseAlternate"), sTID("japaneseAlternate"), sTID("defaultForm"));
    desc36.putDouble(sTID("mojiZume"), 0);
    desc36.putEnumerated(sTID("gridAlignment"), sTID("gridAlignment"), sTID("roman"));
    desc36.putBoolean(sTID("noBreak"), false);
    var desc37 = new ActionDescriptor();
    desc37.putDouble(cTID('Rd  '), 255);
    desc37.putDouble(cTID('Grn '), 255);
    desc37.putDouble(cTID('Bl  '), 255);
    desc36.putObject(cTID('Clr '), sTID("RGBColor"), desc37);
    var desc38 = new ActionDescriptor();
    desc38.putDouble(cTID('Rd  '), 255);
    desc38.putDouble(cTID('Grn '), 255);
    desc38.putDouble(cTID('Bl  '), 255);
    desc36.putObject(sTID("strokeColor"), sTID("RGBColor"), desc38);
    desc35.putObject(cTID('TxtS'), cTID('TxtS'), desc36);
    list5.putObject(cTID('Txtt'), desc35);
    var desc39 = new ActionDescriptor();
    desc39.putInteger(cTID('From'), 4);
    desc39.putInteger(cTID('T   '), 5);
    var desc40 = new ActionDescriptor();
    desc40.putBoolean(sTID("styleSheetHasParent"), true);
    desc40.putString(sTID("fontPostScriptName"), "Arial-Black");
    desc40.putString(cTID('FntN'), "Arial");
    desc40.putString(cTID('FntS'), "Black");
    desc40.putInteger(cTID('Scrp'), 0);
    desc40.putInteger(cTID('FntT'), 1);
    desc40.putBoolean(sTID("fontAvailable"), true);
    desc40.putUnitDouble(cTID('Sz  '), cTID('#Pxl'), 266.670013427734);
    desc40.putUnitDouble(sTID("impliedFontSize"), cTID('#Pxl'), 266.670013427826);
    desc40.putDouble(cTID('HrzS'), 92.9999947547913);
    desc40.putDouble(cTID('VrtS'), 100);
    desc40.putBoolean(sTID("syntheticBold"), false);
    desc40.putBoolean(sTID("syntheticItalic"), false);
    desc40.putBoolean(sTID("autoLeading"), false);
    desc40.putUnitDouble(cTID('Ldng'), cTID('#Pxl'), 516.66650390625);
    desc40.putUnitDouble(sTID("impliedLeading"), cTID('#Pxl'), 516.666503906427);
    desc40.putInteger(cTID('Trck'), 25);
    desc40.putUnitDouble(cTID('Bsln'), cTID('#Pxl'), 0);
    desc40.putUnitDouble(sTID("impliedBaselineShift"), cTID('#Pxl'), 0);
    desc40.putEnumerated(cTID('AtKr'), cTID('AtKr'), sTID("manual"));
    desc40.putEnumerated(sTID("fontCaps"), sTID("fontCaps"), cTID('Nrml'));
    desc40.putEnumerated(sTID("digitSet"), sTID("digitSet"), sTID("arabicDigits"));
    desc40.putEnumerated(sTID("kashidas"), sTID("kashidas"), sTID("kashidaDefault"));
    desc40.putUnitDouble(sTID("diacXOffset"), cTID('#Pxl'), 0);
    desc40.putUnitDouble(sTID("diacYOffset"), cTID('#Pxl'), 0);
    desc40.putUnitDouble(sTID("markYDistFromBaseline"), cTID('#Pxl'), 0);
    desc40.putEnumerated(sTID("baseline"), sTID("baseline"), cTID('Nrml'));
    desc40.putEnumerated(sTID("strikethrough"), sTID("strikethrough"), sTID("strikethroughOff"));
    desc40.putEnumerated(cTID('Undl'), cTID('Undl'), sTID("underlineOff"));
    desc40.putBoolean(sTID("ligature"), true);
    desc40.putBoolean(sTID("altligature"), false);
    desc40.putBoolean(sTID("contextualLigatures"), true);
    desc40.putBoolean(sTID("fractions"), false);
    desc40.putBoolean(sTID("ordinals"), false);
    desc40.putBoolean(sTID("swash"), false);
    desc40.putBoolean(sTID("titling"), false);
    desc40.putBoolean(sTID("connectionForms"), false);
    desc40.putBoolean(sTID("stylisticAlternates"), false);
    desc40.putBoolean(sTID("ornaments"), false);
    desc40.putBoolean(sTID("justificationAlternates"), false);
    desc40.putEnumerated(sTID("figureStyle"), sTID("figureStyle"), cTID('Nrml'));
    desc40.putBoolean(sTID("proportionalMetrics"), false);
    desc40.putBoolean(cTID('kana'), false);
    desc40.putBoolean(sTID("italics"), false);
    desc40.putEnumerated(sTID("baselineDirection"), sTID("baselineDirection"), sTID("withStream"));
    desc40.putEnumerated(sTID("textLanguage"), sTID("textLanguage"), sTID("englishLanguage"));
    desc40.putEnumerated(sTID("japaneseAlternate"), sTID("japaneseAlternate"), sTID("defaultForm"));
    desc40.putDouble(sTID("mojiZume"), 0);
    desc40.putEnumerated(sTID("gridAlignment"), sTID("gridAlignment"), sTID("roman"));
    desc40.putBoolean(sTID("noBreak"), false);
    var desc41 = new ActionDescriptor();
    desc41.putDouble(cTID('Rd  '), 255);
    desc41.putDouble(cTID('Grn '), 255);
    desc41.putDouble(cTID('Bl  '), 255);
    desc40.putObject(cTID('Clr '), sTID("RGBColor"), desc41);
    var desc42 = new ActionDescriptor();
    desc42.putDouble(cTID('Rd  '), 255);
    desc42.putDouble(cTID('Grn '), 255);
    desc42.putDouble(cTID('Bl  '), 255);
    desc40.putObject(sTID("strokeColor"), sTID("RGBColor"), desc42);
    desc39.putObject(cTID('TxtS'), cTID('TxtS'), desc40);
    list5.putObject(cTID('Txtt'), desc39);
    var desc43 = new ActionDescriptor();
    desc43.putInteger(cTID('From'), 5);
    desc43.putInteger(cTID('T   '), 6);
    var desc44 = new ActionDescriptor();
    desc44.putBoolean(sTID("styleSheetHasParent"), true);
    desc44.putString(sTID("fontPostScriptName"), "Arial-Black");
    desc44.putString(cTID('FntN'), "Arial");
    desc44.putString(cTID('FntS'), "Black");
    desc44.putInteger(cTID('Scrp'), 0);
    desc44.putInteger(cTID('FntT'), 1);
    desc44.putBoolean(sTID("fontAvailable"), true);
    desc44.putUnitDouble(cTID('Sz  '), cTID('#Pxl'), 233.330001831055);
    desc44.putUnitDouble(sTID("impliedFontSize"), cTID('#Pxl'), 233.330001831135);
    desc44.putDouble(cTID('HrzS'), 92.9999947547913);
    desc44.putDouble(cTID('VrtS'), 100);
    desc44.putBoolean(sTID("syntheticBold"), false);
    desc44.putBoolean(sTID("syntheticItalic"), false);
    desc44.putBoolean(sTID("autoLeading"), false);
    desc44.putUnitDouble(cTID('Ldng'), cTID('#Pxl'), 516.66650390625);
    desc44.putUnitDouble(sTID("impliedLeading"), cTID('#Pxl'), 516.666503906427);
    desc44.putInteger(cTID('Trck'), 25);
    desc44.putUnitDouble(cTID('Bsln'), cTID('#Pxl'), 0);
    desc44.putUnitDouble(sTID("impliedBaselineShift"), cTID('#Pxl'), 0);
    desc44.putEnumerated(cTID('AtKr'), cTID('AtKr'), sTID("manual"));
    desc44.putEnumerated(sTID("fontCaps"), sTID("fontCaps"), cTID('Nrml'));
    desc44.putEnumerated(sTID("digitSet"), sTID("digitSet"), sTID("arabicDigits"));
    desc44.putEnumerated(sTID("kashidas"), sTID("kashidas"), sTID("kashidaDefault"));
    desc44.putUnitDouble(sTID("diacXOffset"), cTID('#Pxl'), 0);
    desc44.putUnitDouble(sTID("diacYOffset"), cTID('#Pxl'), 0);
    desc44.putUnitDouble(sTID("markYDistFromBaseline"), cTID('#Pxl'), 0);
    desc44.putEnumerated(sTID("baseline"), sTID("baseline"), cTID('Nrml'));
    desc44.putEnumerated(sTID("strikethrough"), sTID("strikethrough"), sTID("strikethroughOff"));
    desc44.putEnumerated(cTID('Undl'), cTID('Undl'), sTID("underlineOff"));
    desc44.putBoolean(sTID("ligature"), true);
    desc44.putBoolean(sTID("altligature"), false);
    desc44.putBoolean(sTID("contextualLigatures"), true);
    desc44.putBoolean(sTID("fractions"), false);
    desc44.putBoolean(sTID("ordinals"), false);
    desc44.putBoolean(sTID("swash"), false);
    desc44.putBoolean(sTID("titling"), false);
    desc44.putBoolean(sTID("connectionForms"), false);
    desc44.putBoolean(sTID("stylisticAlternates"), false);
    desc44.putBoolean(sTID("ornaments"), false);
    desc44.putBoolean(sTID("justificationAlternates"), false);
    desc44.putEnumerated(sTID("figureStyle"), sTID("figureStyle"), cTID('Nrml'));
    desc44.putBoolean(sTID("proportionalMetrics"), false);
    desc44.putBoolean(cTID('kana'), false);
    desc44.putBoolean(sTID("italics"), false);
    desc44.putEnumerated(sTID("baselineDirection"), sTID("baselineDirection"), sTID("withStream"));
    desc44.putEnumerated(sTID("textLanguage"), sTID("textLanguage"), sTID("englishLanguage"));
    desc44.putEnumerated(sTID("japaneseAlternate"), sTID("japaneseAlternate"), sTID("defaultForm"));
    desc44.putDouble(sTID("mojiZume"), 0);
    desc44.putEnumerated(sTID("gridAlignment"), sTID("gridAlignment"), sTID("roman"));
    desc44.putBoolean(sTID("noBreak"), false);
    var desc45 = new ActionDescriptor();
    desc45.putDouble(cTID('Rd  '), 255);
    desc45.putDouble(cTID('Grn '), 255);
    desc45.putDouble(cTID('Bl  '), 255);
    desc44.putObject(cTID('Clr '), sTID("RGBColor"), desc45);
    var desc46 = new ActionDescriptor();
    desc46.putDouble(cTID('Rd  '), 255);
    desc46.putDouble(cTID('Grn '), 255);
    desc46.putDouble(cTID('Bl  '), 255);
    desc44.putObject(sTID("strokeColor"), sTID("RGBColor"), desc46);
    desc43.putObject(cTID('TxtS'), cTID('TxtS'), desc44);
    list5.putObject(cTID('Txtt'), desc43);
    var desc47 = new ActionDescriptor();
    desc47.putInteger(cTID('From'), 6);
    desc47.putInteger(cTID('T   '), 7);
    var desc48 = new ActionDescriptor();
    desc48.putBoolean(sTID("styleSheetHasParent"), true);
    desc48.putString(sTID("fontPostScriptName"), "Arial-Black");
    desc48.putString(cTID('FntN'), "Arial");
    desc48.putString(cTID('FntS'), "Black");
    desc48.putInteger(cTID('Scrp'), 0);
    desc48.putInteger(cTID('FntT'), 1);
    desc48.putBoolean(sTID("fontAvailable"), true);
    desc48.putUnitDouble(cTID('Sz  '), cTID('#Pxl'), 266.670013427734);
    desc48.putUnitDouble(sTID("impliedFontSize"), cTID('#Pxl'), 266.670013427826);
    desc48.putDouble(cTID('HrzS'), 92.9999947547913);
    desc48.putDouble(cTID('VrtS'), 100);
    desc48.putBoolean(sTID("syntheticBold"), false);
    desc48.putBoolean(sTID("syntheticItalic"), false);
    desc48.putBoolean(sTID("autoLeading"), false);
    desc48.putUnitDouble(cTID('Ldng'), cTID('#Pxl'), 516.66650390625);
    desc48.putUnitDouble(sTID("impliedLeading"), cTID('#Pxl'), 516.666503906427);
    desc48.putInteger(cTID('Trck'), 25);
    desc48.putUnitDouble(cTID('Bsln'), cTID('#Pxl'), 0);
    desc48.putUnitDouble(sTID("impliedBaselineShift"), cTID('#Pxl'), 0);
    desc48.putEnumerated(cTID('AtKr'), cTID('AtKr'), sTID("manual"));
    desc48.putEnumerated(sTID("fontCaps"), sTID("fontCaps"), cTID('Nrml'));
    desc48.putEnumerated(sTID("digitSet"), sTID("digitSet"), sTID("arabicDigits"));
    desc48.putEnumerated(sTID("kashidas"), sTID("kashidas"), sTID("kashidaDefault"));
    desc48.putUnitDouble(sTID("diacXOffset"), cTID('#Pxl'), 0);
    desc48.putUnitDouble(sTID("diacYOffset"), cTID('#Pxl'), 0);
    desc48.putUnitDouble(sTID("markYDistFromBaseline"), cTID('#Pxl'), 0);
    desc48.putEnumerated(sTID("baseline"), sTID("baseline"), cTID('Nrml'));
    desc48.putEnumerated(sTID("strikethrough"), sTID("strikethrough"), sTID("strikethroughOff"));
    desc48.putEnumerated(cTID('Undl'), cTID('Undl'), sTID("underlineOff"));
    desc48.putBoolean(sTID("ligature"), true);
    desc48.putBoolean(sTID("altligature"), false);
    desc48.putBoolean(sTID("contextualLigatures"), true);
    desc48.putBoolean(sTID("fractions"), false);
    desc48.putBoolean(sTID("ordinals"), false);
    desc48.putBoolean(sTID("swash"), false);
    desc48.putBoolean(sTID("titling"), false);
    desc48.putBoolean(sTID("connectionForms"), false);
    desc48.putBoolean(sTID("stylisticAlternates"), false);
    desc48.putBoolean(sTID("ornaments"), false);
    desc48.putBoolean(sTID("justificationAlternates"), false);
    desc48.putEnumerated(sTID("figureStyle"), sTID("figureStyle"), cTID('Nrml'));
    desc48.putBoolean(sTID("proportionalMetrics"), false);
    desc48.putBoolean(cTID('kana'), false);
    desc48.putBoolean(sTID("italics"), false);
    desc48.putEnumerated(sTID("baselineDirection"), sTID("baselineDirection"), sTID("withStream"));
    desc48.putEnumerated(sTID("textLanguage"), sTID("textLanguage"), sTID("englishLanguage"));
    desc48.putEnumerated(sTID("japaneseAlternate"), sTID("japaneseAlternate"), sTID("defaultForm"));
    desc48.putDouble(sTID("mojiZume"), 0);
    desc48.putEnumerated(sTID("gridAlignment"), sTID("gridAlignment"), sTID("roman"));
    desc48.putBoolean(sTID("noBreak"), false);
    var desc49 = new ActionDescriptor();
    desc49.putDouble(cTID('Rd  '), 255);
    desc49.putDouble(cTID('Grn '), 255);
    desc49.putDouble(cTID('Bl  '), 255);
    desc48.putObject(cTID('Clr '), sTID("RGBColor"), desc49);
    var desc50 = new ActionDescriptor();
    desc50.putDouble(cTID('Rd  '), 255);
    desc50.putDouble(cTID('Grn '), 255);
    desc50.putDouble(cTID('Bl  '), 255);
    desc48.putObject(sTID("strokeColor"), sTID("RGBColor"), desc50);
    desc47.putObject(cTID('TxtS'), cTID('TxtS'), desc48);
    list5.putObject(cTID('Txtt'), desc47);
    var desc51 = new ActionDescriptor();
    desc51.putInteger(cTID('From'), 7);
    desc51.putInteger(cTID('T   '), 8);
    var desc52 = new ActionDescriptor();
    desc52.putBoolean(sTID("styleSheetHasParent"), true);
    desc52.putString(sTID("fontPostScriptName"), "Arial-Black");
    desc52.putString(cTID('FntN'), "Arial");
    desc52.putString(cTID('FntS'), "Black");
    desc52.putInteger(cTID('Scrp'), 0);
    desc52.putInteger(cTID('FntT'), 1);
    desc52.putBoolean(sTID("fontAvailable"), true);
    desc52.putUnitDouble(cTID('Sz  '), cTID('#Pxl'), 183.330001831055);
    desc52.putUnitDouble(sTID("impliedFontSize"), cTID('#Pxl'), 183.330001831118);
    desc52.putDouble(cTID('HrzS'), 92.9999947547913);
    desc52.putDouble(cTID('VrtS'), 100);
    desc52.putBoolean(sTID("syntheticBold"), false);
    desc52.putBoolean(sTID("syntheticItalic"), false);
    desc52.putBoolean(sTID("autoLeading"), false);
    desc52.putUnitDouble(cTID('Ldng'), cTID('#Pxl'), 516.66650390625);
    desc52.putUnitDouble(sTID("impliedLeading"), cTID('#Pxl'), 516.666503906427);
    desc52.putInteger(cTID('Trck'), 25);
    desc52.putUnitDouble(cTID('Bsln'), cTID('#Pxl'), 0);
    desc52.putUnitDouble(sTID("impliedBaselineShift"), cTID('#Pxl'), 0);
    desc52.putEnumerated(cTID('AtKr'), cTID('AtKr'), sTID("manual"));
    desc52.putEnumerated(sTID("fontCaps"), sTID("fontCaps"), cTID('Nrml'));
    desc52.putEnumerated(sTID("digitSet"), sTID("digitSet"), sTID("arabicDigits"));
    desc52.putEnumerated(sTID("kashidas"), sTID("kashidas"), sTID("kashidaDefault"));
    desc52.putUnitDouble(sTID("diacXOffset"), cTID('#Pxl'), 0);
    desc52.putUnitDouble(sTID("diacYOffset"), cTID('#Pxl'), 0);
    desc52.putUnitDouble(sTID("markYDistFromBaseline"), cTID('#Pxl'), 0);
    desc52.putEnumerated(sTID("baseline"), sTID("baseline"), cTID('Nrml'));
    desc52.putEnumerated(sTID("strikethrough"), sTID("strikethrough"), sTID("strikethroughOff"));
    desc52.putEnumerated(cTID('Undl'), cTID('Undl'), sTID("underlineOff"));
    desc52.putBoolean(sTID("ligature"), true);
    desc52.putBoolean(sTID("altligature"), false);
    desc52.putBoolean(sTID("contextualLigatures"), true);
    desc52.putBoolean(sTID("fractions"), false);
    desc52.putBoolean(sTID("ordinals"), false);
    desc52.putBoolean(sTID("swash"), false);
    desc52.putBoolean(sTID("titling"), false);
    desc52.putBoolean(sTID("connectionForms"), false);
    desc52.putBoolean(sTID("stylisticAlternates"), false);
    desc52.putBoolean(sTID("ornaments"), false);
    desc52.putBoolean(sTID("justificationAlternates"), false);
    desc52.putEnumerated(sTID("figureStyle"), sTID("figureStyle"), cTID('Nrml'));
    desc52.putBoolean(sTID("proportionalMetrics"), false);
    desc52.putBoolean(cTID('kana'), false);
    desc52.putBoolean(sTID("italics"), false);
    desc52.putEnumerated(sTID("baselineDirection"), sTID("baselineDirection"), sTID("withStream"));
    desc52.putEnumerated(sTID("textLanguage"), sTID("textLanguage"), sTID("englishLanguage"));
    desc52.putEnumerated(sTID("japaneseAlternate"), sTID("japaneseAlternate"), sTID("defaultForm"));
    desc52.putDouble(sTID("mojiZume"), 0);
    desc52.putEnumerated(sTID("gridAlignment"), sTID("gridAlignment"), sTID("roman"));
    desc52.putBoolean(sTID("noBreak"), false);
    var desc53 = new ActionDescriptor();
    desc53.putDouble(cTID('Rd  '), 255);
    desc53.putDouble(cTID('Grn '), 255);
    desc53.putDouble(cTID('Bl  '), 255);
    desc52.putObject(cTID('Clr '), sTID("RGBColor"), desc53);
    var desc54 = new ActionDescriptor();
    desc54.putDouble(cTID('Rd  '), 255);
    desc54.putDouble(cTID('Grn '), 255);
    desc54.putDouble(cTID('Bl  '), 255);
    desc52.putObject(sTID("strokeColor"), sTID("RGBColor"), desc54);
    desc51.putObject(cTID('TxtS'), cTID('TxtS'), desc52);
    list5.putObject(cTID('Txtt'), desc51);
    var desc55 = new ActionDescriptor();
    desc55.putInteger(cTID('From'), 8);
    desc55.putInteger(cTID('T   '), 9);
    var desc56 = new ActionDescriptor();
    desc56.putBoolean(sTID("styleSheetHasParent"), true);
    desc56.putString(sTID("fontPostScriptName"), "Arial-Black");
    desc56.putString(cTID('FntN'), "Arial");
    desc56.putString(cTID('FntS'), "Black");
    desc56.putInteger(cTID('Scrp'), 0);
    desc56.putInteger(cTID('FntT'), 1);
    desc56.putBoolean(sTID("fontAvailable"), true);
    desc56.putUnitDouble(cTID('Sz  '), cTID('#Pxl'), 166.669998168945);
    desc56.putUnitDouble(sTID("impliedFontSize"), cTID('#Pxl'), 166.669998169003);
    desc56.putDouble(cTID('HrzS'), 92.9999947547913);
    desc56.putDouble(cTID('VrtS'), 100);
    desc56.putBoolean(sTID("syntheticBold"), false);
    desc56.putBoolean(sTID("syntheticItalic"), false);
    desc56.putBoolean(sTID("autoLeading"), false);
    desc56.putUnitDouble(cTID('Ldng'), cTID('#Pxl'), 516.66650390625);
    desc56.putUnitDouble(sTID("impliedLeading"), cTID('#Pxl'), 516.666503906427);
    desc56.putInteger(cTID('Trck'), 25);
    desc56.putUnitDouble(cTID('Bsln'), cTID('#Pxl'), 0);
    desc56.putUnitDouble(sTID("impliedBaselineShift"), cTID('#Pxl'), 0);
    desc56.putEnumerated(cTID('AtKr'), cTID('AtKr'), sTID("manual"));
    desc56.putEnumerated(sTID("fontCaps"), sTID("fontCaps"), cTID('Nrml'));
    desc56.putEnumerated(sTID("digitSet"), sTID("digitSet"), sTID("arabicDigits"));
    desc56.putEnumerated(sTID("kashidas"), sTID("kashidas"), sTID("kashidaDefault"));
    desc56.putUnitDouble(sTID("diacXOffset"), cTID('#Pxl'), 0);
    desc56.putUnitDouble(sTID("diacYOffset"), cTID('#Pxl'), 0);
    desc56.putUnitDouble(sTID("markYDistFromBaseline"), cTID('#Pxl'), 0);
    desc56.putEnumerated(sTID("baseline"), sTID("baseline"), cTID('Nrml'));
    desc56.putEnumerated(sTID("strikethrough"), sTID("strikethrough"), sTID("strikethroughOff"));
    desc56.putEnumerated(cTID('Undl'), cTID('Undl'), sTID("underlineOff"));
    desc56.putBoolean(sTID("ligature"), true);
    desc56.putBoolean(sTID("altligature"), false);
    desc56.putBoolean(sTID("contextualLigatures"), true);
    desc56.putBoolean(sTID("fractions"), false);
    desc56.putBoolean(sTID("ordinals"), false);
    desc56.putBoolean(sTID("swash"), false);
    desc56.putBoolean(sTID("titling"), false);
    desc56.putBoolean(sTID("connectionForms"), false);
    desc56.putBoolean(sTID("stylisticAlternates"), false);
    desc56.putBoolean(sTID("ornaments"), false);
    desc56.putBoolean(sTID("justificationAlternates"), false);
    desc56.putEnumerated(sTID("figureStyle"), sTID("figureStyle"), cTID('Nrml'));
    desc56.putBoolean(sTID("proportionalMetrics"), false);
    desc56.putBoolean(cTID('kana'), false);
    desc56.putBoolean(sTID("italics"), false);
    desc56.putEnumerated(sTID("baselineDirection"), sTID("baselineDirection"), sTID("withStream"));
    desc56.putEnumerated(sTID("textLanguage"), sTID("textLanguage"), sTID("englishLanguage"));
    desc56.putEnumerated(sTID("japaneseAlternate"), sTID("japaneseAlternate"), sTID("defaultForm"));
    desc56.putDouble(sTID("mojiZume"), 0);
    desc56.putEnumerated(sTID("gridAlignment"), sTID("gridAlignment"), sTID("roman"));
    desc56.putBoolean(sTID("noBreak"), false);
    var desc57 = new ActionDescriptor();
    desc57.putDouble(cTID('Rd  '), 255);
    desc57.putDouble(cTID('Grn '), 255);
    desc57.putDouble(cTID('Bl  '), 255);
    desc56.putObject(cTID('Clr '), sTID("RGBColor"), desc57);
    var desc58 = new ActionDescriptor();
    desc58.putDouble(cTID('Rd  '), 255);
    desc58.putDouble(cTID('Grn '), 255);
    desc58.putDouble(cTID('Bl  '), 255);
    desc56.putObject(sTID("strokeColor"), sTID("RGBColor"), desc58);
    desc55.putObject(cTID('TxtS'), cTID('TxtS'), desc56);
    list5.putObject(cTID('Txtt'), desc55);
    var desc59 = new ActionDescriptor();
    desc59.putInteger(cTID('From'), 9);
    desc59.putInteger(cTID('T   '), 13);
    var desc60 = new ActionDescriptor();
    desc60.putBoolean(sTID("styleSheetHasParent"), true);
    desc60.putString(sTID("fontPostScriptName"), "Arial-Black");
    desc60.putString(cTID('FntN'), "Arial");
    desc60.putString(cTID('FntS'), "Black");
    desc60.putInteger(cTID('Scrp'), 0);
    desc60.putInteger(cTID('FntT'), 1);
    desc60.putBoolean(sTID("fontAvailable"), true);
    desc60.putUnitDouble(cTID('Sz  '), cTID('#Pxl'), 350);
    desc60.putUnitDouble(sTID("impliedFontSize"), cTID('#Pxl'), 350.00000000012);
    desc60.putDouble(cTID('HrzS'), 92.9999947547913);
    desc60.putDouble(cTID('VrtS'), 100);
    desc60.putBoolean(sTID("syntheticBold"), false);
    desc60.putBoolean(sTID("syntheticItalic"), false);
    desc60.putBoolean(sTID("autoLeading"), false);
    desc60.putUnitDouble(cTID('Ldng'), cTID('#Pxl'), 516.66650390625);
    desc60.putUnitDouble(sTID("impliedLeading"), cTID('#Pxl'), 516.666503906427);
    desc60.putInteger(cTID('Trck'), 25);
    desc60.putUnitDouble(cTID('Bsln'), cTID('#Pxl'), 0);
    desc60.putUnitDouble(sTID("impliedBaselineShift"), cTID('#Pxl'), 0);
    desc60.putEnumerated(cTID('AtKr'), cTID('AtKr'), sTID("manual"));
    desc60.putEnumerated(sTID("fontCaps"), sTID("fontCaps"), cTID('Nrml'));
    desc60.putEnumerated(sTID("digitSet"), sTID("digitSet"), sTID("arabicDigits"));
    desc60.putEnumerated(sTID("kashidas"), sTID("kashidas"), sTID("kashidaDefault"));
    desc60.putUnitDouble(sTID("diacXOffset"), cTID('#Pxl'), 0);
    desc60.putUnitDouble(sTID("diacYOffset"), cTID('#Pxl'), 0);
    desc60.putUnitDouble(sTID("markYDistFromBaseline"), cTID('#Pxl'), 0);
    desc60.putEnumerated(sTID("baseline"), sTID("baseline"), cTID('Nrml'));
    desc60.putEnumerated(sTID("strikethrough"), sTID("strikethrough"), sTID("strikethroughOff"));
    desc60.putEnumerated(cTID('Undl'), cTID('Undl'), sTID("underlineOff"));
    desc60.putBoolean(sTID("ligature"), true);
    desc60.putBoolean(sTID("altligature"), false);
    desc60.putBoolean(sTID("contextualLigatures"), true);
    desc60.putBoolean(sTID("fractions"), false);
    desc60.putBoolean(sTID("ordinals"), false);
    desc60.putBoolean(sTID("swash"), false);
    desc60.putBoolean(sTID("titling"), false);
    desc60.putBoolean(sTID("connectionForms"), false);
    desc60.putBoolean(sTID("stylisticAlternates"), false);
    desc60.putBoolean(sTID("ornaments"), false);
    desc60.putBoolean(sTID("justificationAlternates"), false);
    desc60.putEnumerated(sTID("figureStyle"), sTID("figureStyle"), cTID('Nrml'));
    desc60.putBoolean(sTID("proportionalMetrics"), false);
    desc60.putBoolean(cTID('kana'), false);
    desc60.putBoolean(sTID("italics"), false);
    desc60.putEnumerated(sTID("baselineDirection"), sTID("baselineDirection"), sTID("withStream"));
    desc60.putEnumerated(sTID("textLanguage"), sTID("textLanguage"), sTID("englishLanguage"));
    desc60.putEnumerated(sTID("japaneseAlternate"), sTID("japaneseAlternate"), sTID("defaultForm"));
    desc60.putDouble(sTID("mojiZume"), 0);
    desc60.putEnumerated(sTID("gridAlignment"), sTID("gridAlignment"), sTID("roman"));
    desc60.putBoolean(sTID("noBreak"), false);
    var desc61 = new ActionDescriptor();
    desc61.putDouble(cTID('Rd  '), 255);
    desc61.putDouble(cTID('Grn '), 255);
    desc61.putDouble(cTID('Bl  '), 255);
    desc60.putObject(cTID('Clr '), sTID("RGBColor"), desc61);
    var desc62 = new ActionDescriptor();
    desc62.putDouble(cTID('Rd  '), 255);
    desc62.putDouble(cTID('Grn '), 255);
    desc62.putDouble(cTID('Bl  '), 255);
    desc60.putObject(sTID("strokeColor"), sTID("RGBColor"), desc62);
    desc59.putObject(cTID('TxtS'), cTID('TxtS'), desc60);
    list5.putObject(cTID('Txtt'), desc59);
    desc2.putList(cTID('Txtt'), list5);
    var list6 = new ActionList();
    var desc63 = new ActionDescriptor();
    desc63.putInteger(cTID('From'), 0);
    desc63.putInteger(cTID('T   '), 13);
    var desc64 = new ActionDescriptor();
    desc64.putBoolean(sTID("styleSheetHasParent"), true);
    desc64.putEnumerated(cTID('Algn'), cTID('Alg '), cTID('Left'));
    desc64.putEnumerated(sTID("directionType"), sTID("directionType"), sTID("dirLeftToRight"));
    desc64.putEnumerated(sTID("textComposerEngine"), sTID("textComposerEngine"), sTID("textLatinCJKComposer"));
    desc63.putObject(sTID("paragraphStyle"), sTID("paragraphStyle"), desc64);
    list6.putObject(sTID("paragraphStyleRange"), desc63);
    desc2.putList(sTID("paragraphStyleRange"), list6);
    var list7 = new ActionList();
    desc2.putList(sTID("kerningRange"), list7);
    desc1.putObject(cTID('T   '), cTID('TxLr'), desc2);
    executeAction(cTID('setd'), desc1, dialogMode);
  };

  step1();      // Select
  step2();      // Select
  step3();      // Set
};



//=========================================
//                    Sizes3.main
//=========================================
//

Sizes3.main = function () {
  Sizes3();
};

Sizes3.main();

// EOF

"change_back_dob.jsx"
// EOF
